import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import { DemoRepository, demoSeed } from '../src/demo.ts';
import { calculateShares, reportFor, billRemaining, duplicateCandidates, derive, emptySnapshot, filterRows, assertDecimalPayload, cashFlows, type Bill } from '../src/domain.ts';
import { parseText, parseQR } from '../src/import.ts';
import { fromZonedTime } from '../src/timezone.ts';
import { csv, filteredCSV, exportCSVs, demoArchive } from '../src/export.ts';
import { unzipSync, strFromU8 } from 'fflate';

const fixture = JSON.parse(readFileSync(new URL('../../../tests/fixtures/import-v1.json', import.meta.url), 'utf8'));
const splitPayload = (payer = 'self') => ({ p_client_mutation_id: crypto.randomUUID(), p_total: '120000', p_title: 'Makan bersama', p_category_id: 'food', p_payer_kind: payer, p_payer_account_id: payer === 'self' ? 'cash' : null, p_payer_member_id: payer === 'other' ? 'friend' : null, p_occurred_at: '2026-09-30T05:00:00Z', p_members: [{ id: 'self', display_name: 'Saya', is_self: true, share_amount: '40000', sort_order: 0 }, { id: 'friend', display_name: 'Ani', is_self: false, share_amount: '40000', sort_order: 1 }, { id: 'friend2', display_name: 'Budi', is_self: false, share_amount: '40000', sort_order: 2 }] });
function isolated() { const repository = new DemoRepository(); repository.data.transactions = []; repository.data.splitBills = []; return repository; }
test('seed shared: exact 200 transactions, 3 months; reset discards mutations', async () => { const repository = new DemoRepository(); assert.equal(repository.data.transactions.length, 200); assert.equal(new Set(repository.data.transactions.map(row => row.occurredAt.slice(0,7))).size, 3); repository.data.transactions.pop(); repository.reset(); assert.deepEqual(repository.data, demoSeed()); });
test('QR/CRC golden import fixture', () => { for (const item of fixture.qris) { if (item.error) assert.throws(() => parseQR(item.raw)); else assert.deepEqual(parseQR(item.raw), item.expected); } });
test('text golden: explicit total only; ambiguous subtotal never guessed', () => { for (const item of fixture.text) { const review = parseText(item.raw); assert.equal(review.amount.value, item.expected_amount); assert.equal(review.amount.confidence, item.expected_confidence); } });
test('invalid date and multiple totals require user confirmation', () => { assert.equal(parseText('TOKO\nTotal 10.000\nTotal 20.000\n31/02/2026').amount.value, null); assert.equal(parseText('TOKO\n31/02/2026').date.value, null); });
test('equal/percentage/amount share validation', () => { assert.deepEqual(calculateShares('101', [{ id:'a', value:'0' },{ id:'b', value:'0' }], 'equal'), { a:'51', b:'50' }); assert.throws(() => calculateShares('100', [{ id:'a', value:'49' },{ id:'b', value:'50' }], 'amount')); assert.throws(() => calculateShares('100', [{ id:'a', value:'33.333' },{ id:'b', value:'66.667' }], 'percentage')); });
test('§3.5 self-paid: cash -120000, expense 40000, receivable 80000', async () => { const repository = isolated(); await repository.mutate('create_split_bill', splitPayload()); const data = await repository.snapshot(); assert.equal(data.accounts[0].balance, '380000'); assert.equal(data.overview.personalExpense, '40000'); assert.equal(data.overview.receivables, '80000'); assert.equal(data.overview.netPosition, '2960000'); });
test('§3.5 friend-paid: cash unchanged, expense 40000, payable 40000', async () => { const repository = isolated(); await repository.mutate('create_split_bill', splitPayload('other')); const data = await repository.snapshot(); assert.equal(data.accounts[0].balance, '500000'); assert.equal(data.overview.personalExpense, '40000'); assert.equal(data.overview.payables, '40000'); assert.equal(data.overview.netPosition, '2960000'); });
test('settlements change cash, not expense/income/budget; overpay rejected', async () => { const repository = isolated(); await repository.mutate('create_split_bill', splitPayload()); const bill = repository.data.splitBills[0]; const payload = { p_client_mutation_id: crypto.randomUUID(), p_split_bill_id: bill.id, p_member_id: 'friend', p_account_id:'cash', p_amount:'15000', p_occurred_at:'2026-09-30T06:00:00Z' }; await repository.mutate('record_split_settlement', payload); const data = await repository.snapshot(); assert.equal(data.accounts[0].balance, '395000'); assert.equal(data.overview.personalExpense, '40000'); assert.equal(data.overview.personalIncome, '0'); assert.equal(data.overview.receivables, '65000'); await assert.rejects(repository.mutate('record_split_settlement', { ...payload, p_client_mutation_id: crypto.randomUUID(), p_amount:'25001' })); });
test('writeoff noncash + reversal preserves account and reporting', async () => { const repository = isolated(); await repository.mutate('create_split_bill', splitPayload()); const bill = repository.data.splitBills[0]; await repository.mutate('record_split_resolution', { p_client_mutation_id: crypto.randomUUID(), p_split_bill_id:bill.id, p_member_id:'friend', p_amount:'10000', p_reason:'Dihapus atas keputusan pengguna', p_occurred_at:'2026-09-30T06:00:00Z' }); let data = await repository.snapshot(); assert.equal(data.accounts[0].balance,'380000'); assert.equal(data.overview.personalExpense,'50000'); const event = data.splitBills[0].resolutions[0]; await repository.mutate('reverse_split_resolution', { p_client_mutation_id:crypto.randomUUID(), p_resolution_id:event.id, p_expected_version:1, p_reason:'Koreksi' }); data = await repository.snapshot(); assert.equal(data.overview.personalExpense,'40000'); assert.equal(data.overview.receivables,'80000'); });
test('friend payable forgiveness is noncash income', async () => { const repository = isolated(); await repository.mutate('create_split_bill', splitPayload('other')); await repository.mutate('record_split_resolution', { p_split_bill_id:repository.data.splitBills[0].id, p_member_id:'friend', p_amount:'10000', p_reason:'Dibebaskan', p_occurred_at:'2026-09-30T06:00:00Z' }); const data=await repository.snapshot(); assert.equal(data.overview.personalIncome,'10000'); assert.equal(data.overview.payables,'30000'); assert.equal(data.accounts[0].balance,'500000'); });
test('active settlement locks structure/delete', async () => { const repository = isolated(); await repository.mutate('create_split_bill',splitPayload()); const bill=repository.data.splitBills[0]; await repository.mutate('record_split_settlement',{ p_split_bill_id:bill.id,p_member_id:'friend',p_account_id:'cash',p_amount:'1',p_occurred_at:'2026-09-30T06:00:00Z' }); await assert.rejects(repository.mutate('update_split_bill',{ ...splitPayload(),p_split_bill_id:bill.id,p_expected_version:2 })); await assert.rejects(repository.mutate('delete_split_bill',{p_split_bill_id:bill.id,p_expected_version:2})); });
test('idempotency + stale version + failed mutation rollback', async () => { const repository = isolated(); const payload=splitPayload(); await repository.mutate('create_split_bill',payload); await repository.mutate('create_split_bill',payload); assert.equal(repository.data.splitBills.length,1); await assert.rejects(repository.mutate('create_split_bill',{...payload,p_total:'1'}), /DUPLICATE_MUTATION/); const before=await repository.snapshot(); await assert.rejects(repository.mutate('delete_split_bill',{p_split_bill_id:before.splitBills[0].id,p_expected_version:0}), /VERSION_CONFLICT/); assert.deepEqual(await repository.snapshot(),before); });
test('transfer is atomic; same account rejected; edit/delete/restore no expense', async () => { const repository = isolated(); const payload={p_from_account_id:'cash',p_to_account_id:'bank',p_amount:'100',p_occurred_at:'2026-09-30T05:00:00Z'}; await assert.rejects(repository.mutate('create_transfer',{...payload,p_to_account_id:'cash'})); await repository.mutate('create_transfer',payload); let data=await repository.snapshot(); assert.equal(data.overview.accountBalance,'3000000'); assert.equal(data.overview.personalExpense,'0'); const row=data.transfers[0]; await repository.mutate('delete_transfer',{p_transfer_id:row.id,p_expected_version:1}); await repository.mutate('restore_transfer',{p_transfer_id:row.id,p_expected_version:2}); data=await repository.snapshot(); assert.equal(data.accounts[0].balance,'499900'); });
test('review never affects balances before explicit confirm; confirm only once', async () => { const repository = isolated(); const before=await repository.snapshot(); const review=parseText('TOKO\nTotal: Rp75.000\n30/09/2026'); await repository.mutate('add_review_item',review); assert.deepEqual((await repository.snapshot()).overview,before.overview); const payload={id:review.id,transaction:{kind:'expense',amount:'75000',accountID:'cash',categoryID:'food',occurredAt:'2026-09-30T05:00:00Z',source:'pasted_text'}}; await repository.mutate('confirm_review_item',payload); await assert.rejects(repository.mutate('confirm_review_item',payload)); assert.equal(repository.data.transactions.length,1); });
test('review-to-split and posted conversion replace original impact atomically', async () => { const repository = isolated(); const review=parseText('TOKO\nTotal 120.000'); await repository.mutate('add_review_item',review); await repository.mutate('create_split_bill_from_review',{...splitPayload(),p_review_item_id:review.id}); assert.equal(repository.data.reviewItems.find(row=>row.id===review.id)?.status,'saved'); await repository.mutate('create_transaction',{p_type:'expense',p_amount:'120000',p_account_id:'cash',p_category_id:'food',p_occurred_at:'2026-09-30T05:00:00Z'}); const transaction=repository.data.transactions[0]; await repository.mutate('convert_transaction_to_split_bill',{...splitPayload(),p_transaction_id:transaction.id,p_expected_version:1}); const data=await repository.snapshot(); assert.equal(data.overview.personalExpense,'80000'); assert.equal(data.accounts[0].balance,'260000'); });
test('duplicate uses bill total, ±2 days, normalized merchant, selected account', () => { const data=demoSeed(); const review=parseText('Makan bersama\nTotal 120.000\n25/09/2026'); assert.equal(duplicateCandidates(data,review,'cash')[0].id,'demo-bill-self'); assert.equal(duplicateCandidates(data,review,'bank').length,0); review.amount.value='40000'; assert.equal(duplicateCandidates(data,review,'cash').length,0); });
test('filter/CSV share same row set and stable keyset order', () => { const data=demoSeed(); const filter={query:'',kind:'expense',account:'cash',category:'food',from:'2026-09-01',to:'2026-09-30'}; const rows=filterRows(data,filter); assert.equal(filteredCSV(data,filter,'Asia/Jakarta').split('\r\n').length-2,rows.length); assert.ok(rows.every(row=>row.kind==='expense' && row.accountID==='cash' && row.categoryID==='food')); });
test('CSV BOM, decimal negative numbers, text formula escape', () => { const value=csv([['note','amount'],['=SUM(A1)','-100'],['@evil','100']], [1]); assert.ok(value.startsWith('\ufeff')); assert.match(value, /"'=SUM\(A1\)"/); assert.match(value,/"-100"/); assert.match(value,/"'@evil"/); });
test('full ZIP has six CSVs, versioned data, verified SHA manifest', async () => { const archive=await demoArchive(demoSeed(),new Map()); const files=unzipSync(new Uint8Array(await archive.arrayBuffer())); assert.equal(Object.keys(files).length,8); const manifest=JSON.parse(strFromU8(files['manifest.json'])); assert.equal(manifest.file_count,7); for (const file of manifest.files) { const digest=await crypto.subtle.digest('SHA-256',new Uint8Array(files[file.name])); assert.equal(Buffer.from(digest).toString('hex'),file.sha256); assert.equal(file.bytes,files[file.name].length); } });
test('last active account, duplicate category name and archived category prevented', async () => { const repository = isolated(); await repository.mutate('archive_account',{id:'bank',expected_version:1}); await assert.rejects(repository.mutate('archive_account',{id:'cash',expected_version:1})); await assert.rejects(repository.mutate('create_category',{p_name:'makan',p_kind:'expense',p_sort_order:0})); await repository.mutate('archive_category',{id:'food',expected_version:1}); await assert.rejects(repository.mutate('create_transaction',{p_type:'expense',p_amount:'1',p_account_id:'cash',p_category_id:'food',p_occurred_at:'2026-09-30T05:00:00Z'})); });
test('timezone period boundaries use local day, not UTC date substring', () => { assert.equal(fromZonedTime('2026-09-01','Asia/Jakarta'),'2026-08-31T17:00:00.000Z'); assert.equal(fromZonedTime('2026-09-01','Asia/Jayapura'),'2026-08-31T15:00:00.000Z'); const data=emptySnapshot(); data.transactions.push({id:'boundary',kind:'expense',amount:'100',accountID:'cash',categoryID:'food',occurredAt:'2026-08-31T17:00:00Z',deleted:false,source:'manual',version:1}); assert.equal(reportFor(data,'2026-09-01','2026-09-30').personalExpense,'100'); });
test('all demo derived financial totals remain decimal strings', () => { const data=derive(demoSeed()); assert.ok(Object.values(data.overview).every(value=>typeof value==='string' && /^-?\d+$/.test(value))); for (const bill of data.splitBills) assert.ok(billRemaining(bill as Bill)>=0n); assert.equal(Object.keys(exportCSVs(data)).length,6); });
test('snapshot rejects JSON numbers including extraction field values', () => {
  assert.doesNotThrow(() => assertDecimalPayload(demoSeed()));
  assert.throws(() => assertDecimalPayload({ transactions: [{ amount: 100 }] }));
  assert.throws(() => assertDecimalPayload({ reviewItems: [{ amount: { value: 100 } }] }));
});
test('six CSV headers match shared contract; expense and cash sums match period reports', () => {
  const headers = JSON.parse(readFileSync(new URL('../../../contracts/v1/export-headers.json', import.meta.url), 'utf8'));
  const data = demoSeed(), files = exportCSVs(data, '2026-09-01', '2026-09-30');
  for (const [name, value] of Object.entries(files)) assert.equal(value.split('\r\n')[0], '\ufeff' + headers[name].map((header: string) => `"${header}"`).join(','));
  const sum = (name: keyof typeof files) => files[name].split('\r\n').slice(1).filter(Boolean).reduce((total, line) => total + BigInt(line.split(',')[4].replaceAll('"', '')), 0n);
  assert.equal(sum('personal_expenses.csv').toString(), reportFor(data, '2026-09-01', '2026-09-30').personalExpense);
  assert.equal(sum('cash_flow.csv'), cashFlows(data, '2026-09-01', '2026-09-30').reduce((total, row) => total + BigInt(row.net), 0n));
});
test('duplicate bill merge marks review without changing balances or reports', async () => {
  const repository = new DemoRepository(), before = await repository.snapshot();
  const review = parseText('Makan bersama\nTotal 120.000');
  await repository.mutate('add_review_item', review);
  await repository.mutate('merge_review_item', { id: review.id, bill_id: 'demo-bill-self' });
  const after = await repository.snapshot();
  assert.equal(after.reviewItems.find(row => row.id === review.id)?.status, 'merged');
  assert.deepEqual(after.overview, before.overview);
  assert.deepEqual(after.accounts, before.accounts);
});
