"""Generate the shared calculator forms and source notes for web and iOS."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
categories = [
    ("shopping", "Belanja dan promo", "tag"), ("daily", "Biaya sehari-hari", "house"),
    ("personal", "Keuangan pribadi", "wallet"), ("debt", "Cicilan dan utang", "bank"),
    ("business", "Usaha dan penjualan", "chart"), ("zakat", "Zakat", "moon"),
    ("obligations", "Fidyah dan kafarat", "moon"), ("inheritance", "Warisan dan wasiat", "people")
]
sources = {
    "q9_103": dict(title="At-Taubah 9:103", status="Al-Qur'an", url="https://quran.com/9/103", meaning="Perintah mengambil zakat dari harta untuk membersihkan dan menyucikan pemiliknya."),
    "q2_267": dict(title="Al-Baqarah 2:267", status="Al-Qur'an", url="https://quran.com/2/267", meaning="Perintah menginfakkan sebagian hasil usaha yang baik dan hasil bumi."),
    "b1454": dict(title="Shahih al-Bukhari 1454", status="Sahih", url="https://sunnah.com/bukhari:1454", meaning="Surat Abu Bakar memuat ketentuan zakat unta, kambing, serta perak sebesar seperempat dari sepersepuluh (2,5%)."),
    "d1573": dict(title="Sunan Abu Dawud 1573", status="Sahih menurut al-Albani", url="https://sunnah.com/abudawud:1573", meaning="Riwayat Ali menyebut zakat dua ratus dirham setelah satu tahun dan dua puluh dinar dengan zakat setengah dinar."),
    "d1576": dict(title="Sunan Abu Dawud 1576", status="Sahih menurut al-Albani", url="https://sunnah.com/abudawud:1576", meaning="Muadz diperintahkan mengambil seekor tabi atau tabiah untuk setiap tiga puluh sapi dan seekor musinnah untuk setiap empat puluh sapi."),
    "b1483": dict(title="Shahih al-Bukhari 1483", status="Sahih", url="https://sunnah.com/bukhari:1483", meaning="Hasil yang diairi hujan atau sumber alami dikenai sepersepuluh; yang diairi dengan pengangkutan air dikenai setengahnya."),
    "b1405": dict(title="Shahih al-Bukhari 1405", status="Sahih", url="https://sunnah.com/bukhari:1405", meaning="Tidak ada zakat pada hasil kurang dari lima wasaq, perak kurang dari lima uqiyah, dan unta kurang dari lima ekor."),
    "b1499": dict(title="Shahih al-Bukhari 1499", status="Sahih", url="https://sunnah.com/bukhari:1499", meaning="Pada rikaz terdapat kewajiban seperlima (20%). Penentuan apakah temuan termasuk rikaz memerlukan pemeriksaan sifat harta."),
    "b1503": dict(title="Shahih al-Bukhari 1503", status="Sahih", url="https://sunnah.com/bukhari:1503", meaning="Rasulullah mewajibkan zakat fitrah satu sha kurma atau gandum atas kaum Muslim, kecil maupun besar, dan memerintahkannya sebelum salat Id."),
    "q2_184": dict(title="Al-Baqarah 2:184", status="Al-Qur'an", url="https://quran.com/2/184", meaning="Ayat menyebut fidyah berupa memberi makan orang miskin bagi kondisi yang diterangkan dalam ketentuan puasa."),
    "b4505": dict(title="Shahih al-Bukhari 4505", status="Sahih; penjelasan Ibnu Abbas", url="https://sunnah.com/bukhari:4505", meaning="Ibnu Abbas menjelaskan orang lanjut usia yang tidak mampu berpuasa memberi makan seorang miskin untuk setiap hari."),
    "q5_89": dict(title="Al-Ma'idah 5:89", status="Al-Qur'an", url="https://quran.com/5/89", meaning="Kafarat sumpah: memberi makan sepuluh orang miskin dengan makanan pertengahan keluarga, memberi pakaian, atau membebaskan budak. Orang yang tidak mampu berpuasa tiga hari."),
    "b1936": dict(title="Shahih al-Bukhari 1936", status="Sahih", url="https://sunnah.com/bukhari:1936", meaning="Dalam kasus hubungan suami istri pada siang Ramadan, Nabi menjelaskan urutan membebaskan budak, berpuasa dua bulan berturut-turut, lalu memberi makan enam puluh orang miskin ketika tidak mampu."),
    "q4_11": dict(title="An-Nisa 4:11", status="Al-Qur'an", url="https://quran.com/4/11", meaning="Bagian anak dan orang tua, dengan ketentuan penyelesaian wasiat dan utang sebelum pembagian."),
    "q4_12": dict(title="An-Nisa 4:12", status="Al-Qur'an", url="https://quran.com/4/12", meaning="Bagian suami, istri, dan saudara seibu, setelah wasiat dan utang diselesaikan."),
    "q4_176": dict(title="An-Nisa 4:176", status="Al-Qur'an", url="https://quran.com/4/176", meaning="Ketentuan kalalah dan bagian saudara pada kondisi yang memenuhi syarat."),
    "b6732": dict(title="Shahih al-Bukhari 6732", status="Sahih", url="https://sunnah.com/bukhari:6732", meaning="Berikan bagian yang ditentukan kepada pemiliknya; sisanya untuk kerabat laki-laki terdekat yang berhak."),
    "b6736": dict(title="Shahih al-Bukhari 6736", status="Sahih", url="https://sunnah.com/bukhari:6736", meaning="Dalam kasus anak perempuan, cucu perempuan dari anak laki-laki, dan saudara perempuan: anak perempuan mendapat setengah, cucu perempuan seperenam untuk melengkapi dua pertiga, dan saudara perempuan menerima sisa."),
    "d2870": dict(title="Sunan Abu Dawud 2870", status="Hasan sahih menurut al-Albani", url="https://sunnah.com/abudawud:2870", meaning="Allah telah memberikan hak kepada setiap pemilik hak; tidak ada wasiat untuk ahli waris. Penerapan wasiat khusus dengan persetujuan ahli waris merupakan ketentuan fikih tersendiri."),
    "b2742": dict(title="Shahih al-Bukhari 2742", status="Sahih", url="https://sunnah.com/bukhari:2742", meaning="Dalam pembicaraan dengan Saad, Nabi membolehkan wasiat sepertiga dan menyatakan sepertiga itu banyak."),
}

def field(key, label, kind="money", default="", **kw):
    return dict(key=key, label=label, kind=kind, default=default, **kw)

def choice(key, label, options, default=None, **kw):
    return field(key, label, "choice", default or options[0][0], options=[dict(value=v, label=t) for v, t in options], **kw)

def check(key, label, default="false", **kw):
    return field(key, label, "toggle", default, **kw)

def amount(key, label, default="", **kw): return field(key, label, "money", default, **kw)
def number(key, label, default="", **kw): return field(key, label, "decimal", default, **kw)
def integer(key, label, default="", **kw): return field(key, label, "integer", default, **kw)
def percent(key, label, default="", **kw): return field(key, label, "percent", default, **kw)

catalog = []
def add(id, title, category, description, fields, notes, refs=None, method=None):
    catalog.append(dict(id=id, title=title, category=category, description=description, fields=fields, notes=notes,
        references=refs or [], method=method or "Perhitungan estimasi berdasarkan angka yang Anda masukkan."))

add("discount", "Diskon", "shopping", "Harga akhir dan jumlah penghematan.", [amount("price", "Harga awal"), percent("discount", "Diskon (%)")], ["Diskon diterapkan pada harga awal. Harga akhir dibulatkan ke Rupiah terdekat."])
add("stacked-discount", "Diskon bertingkat", "shopping", "Hitung diskon berurutan, misalnya 20% lalu 10%.", [amount("price", "Harga awal"), percent("first", "Diskon pertama (%)"), percent("second", "Diskon kedua (%)"), percent("third", "Diskon ketiga (%)", "0")], ["Persentase diskon tidak dijumlahkan. Setiap diskon diterapkan pada sisa harga sebelumnya."])
add("tax-tip", "Pajak, service, dan tip", "shopping", "Rincian tambahan biaya sampai total pembayaran.", [amount("subtotal", "Subtotal"), percent("service", "Service (%)", "0"), percent("tax", "Pajak (%)", "0"), choice("taxBase", "Dasar pajak", [("subtotal", "Subtotal"), ("with-service", "Subtotal + service")]), percent("tip", "Tip (%)", "0"), choice("tipBase", "Dasar tip", [("subtotal", "Subtotal"), ("total", "Total setelah service dan pajak")])], ["Tarif pajak dan service diisi sesuai tagihan. Setiap komponen dibulatkan ke Rupiah."])
add("unit-price", "Harga per satuan", "shopping", "Bandingkan dua produk menggunakan satuan yang sama.", [amount("priceA", "Harga produk A"), number("quantityA", "Isi produk A", unit="gram / ml / buah", min="0.000001"), amount("priceB", "Harga produk B"), number("quantityB", "Isi produk B", unit="gram / ml / buah", min="0.000001")], ["Samakan satuan kedua produk sebelum membandingkan. Hasil harga satuan ditampilkan hingga enam desimal."])
add("promo", "Promo dan cashback", "shopping", "Bandingkan biaya efektif dua penawaran.", [amount("priceA", "Total harga penawaran A"), percent("discountA", "Diskon A (%)", "0"), amount("deliveryA", "Ongkir / biaya A", "0"), percent("cashbackA", "Cashback A (%)", "0"), amount("capA", "Batas cashback A (0 = tanpa batas)", "0"), amount("priceB", "Total harga penawaran B"), percent("discountB", "Diskon B (%)", "0"), amount("deliveryB", "Ongkir / biaya B", "0"), percent("cashbackB", "Cashback B (%)", "0"), amount("capB", "Batas cashback B (0 = tanpa batas)", "0")], ["Cashback dihitung dari harga setelah diskon, tanpa ongkir. Cashback dapat berupa saldo promo dengan syarat pemakaian; biaya efektif berbeda dari uang yang dibayar sekarang."])
add("subscriptions", "Biaya langganan", "daily", "Bandingkan paket bulanan dengan paket tahunan.", [amount("monthly", "Biaya paket bulanan"), amount("annual", "Biaya paket tahunan"), integer("months", "Lama penggunaan (bulan)", "12", min="1", max="120")], ["Paket tahunan dibeli untuk setiap periode 12 bulan yang dimulai. Pajak dan biaya tambahan harus sudah termasuk harga."])
add("travel", "Biaya perjalanan", "daily", "Total transportasi, penginapan, makan, dan aktivitas.", [integer("people", "Jumlah pelancong", "1", min="1", max="100"), integer("days", "Jumlah hari", "1", min="1", max="365"), integer("nights", "Jumlah malam", "0", max="365"), integer("rooms", "Jumlah kamar", "1", min="1", max="100"), amount("transport", "Transportasi per orang", "0"), amount("hotel", "Harga kamar per malam", "0"), amount("food", "Makan per orang per hari", "0"), amount("activities", "Aktivitas per orang", "0"), amount("other", "Biaya lain seluruh rombongan", "0"), percent("reserve", "Cadangan biaya (%)", "0")], ["Transportasi diisi total pulang-pergi. Kamar dihitung per malam; biaya lain berlaku untuk seluruh rombongan. Template haji/umrah memakai rincian ini."])
add("vehicle", "Biaya kendaraan", "daily", "Biaya perjalanan dan biaya per kilometer.", [number("distance", "Jarak perjalanan", unit="km", min="0.000001"), number("efficiency", "Efisiensi BBM", unit="km/liter", min="0.000001"), amount("fuelPrice", "Harga BBM per liter"), amount("toll", "Tol", "0"), amount("parking", "Parkir", "0"), amount("maintenance", "Cadangan servis per kilometer", "0")], ["Jarak harus mencakup seluruh perjalanan. Estimasi konsumsi BBM dipengaruhi kendaraan, lalu lintas, dan kondisi jalan."])
add("electricity", "Biaya listrik", "daily", "Estimasi konsumsi dan biaya satu jenis perangkat.", [number("watts", "Daya perangkat", unit="watt"), number("hours", "Pemakaian per hari", unit="jam", max="24"), integer("devices", "Jumlah perangkat", "1", min="1", max="1000"), integer("days", "Jumlah hari", "30", min="1", max="366"), number("tariff", "Tarif listrik", unit="Rp/kWh", min="0.000001"), amount("fixed", "Biaya tetap / administrasi", "0"), percent("tax", "Pajak / tambahan (%)", "0")], ["Tarif diisi sesuai golongan listrik. Estimasi daya rata-rata dapat berbeda dari daya maksimum pada label perangkat."])
add("housing", "Kos atau kontrakan", "daily", "Bandingkan biaya tinggal selama periode yang sama.", [integer("months", "Lama tinggal (bulan)", "12", min="1", max="120"), amount("rentA", "Sewa bulanan kos A"), amount("utilitiesA", "Utilitas bulanan A", "0"), amount("commuteA", "Transportasi bulanan A", "0"), amount("setupA", "Biaya awal yang tidak kembali A", "0"), amount("depositA", "Deposit yang dapat kembali A", "0"), amount("rentB", "Sewa bulanan kontrakan B"), amount("utilitiesB", "Utilitas bulanan B", "0"), amount("commuteB", "Transportasi bulanan B", "0"), amount("setupB", "Biaya awal yang tidak kembali B", "0"), amount("depositB", "Deposit yang dapat kembali B", "0")], ["Deposit ditampilkan sebagai kebutuhan uang awal, terpisah dari biaya tinggal. Masukkan sewa tahunan sebagai ekuivalen bulanan."])
add("emergency", "Dana darurat", "personal", "Kebutuhan cadangan berdasarkan biaya hidup.", [amount("monthly", "Pengeluaran wajib bulanan"), integer("months", "Bulan perlindungan", "6", min="1", max="36"), amount("available", "Dana darurat tersedia", "0")], ["Jumlah bulan dipilih berdasarkan tanggungan, kestabilan penghasilan, dan kebutuhan Anda. Target dapat diterapkan ke fitur Target yang sudah tersedia."])
add("wage", "Gaji per jam atau hari", "personal", "Nilai waktu kerja dari pendapatan bersih.", [amount("salary", "Pendapatan bersih bulanan"), integer("days", "Hari kerja per bulan", "22", min="1", max="31"), number("hours", "Jam kerja per hari", "8", min="0.000001", max="24")], ["Perhitungan ini tidak menentukan hak upah lembur atau kewajiban ketenagakerjaan."])
add("compound", "Bunga majemuk", "personal", "Simulasi pertumbuhan dengan setoran rutin.", [amount("principal", "Simpanan awal", "0"), amount("contribution", "Setoran bulanan", "0"), percent("annualRate", "Imbal hasil nominal tahunan (%)", "0", max="100"), integer("months", "Lama simpan (bulan)", "12", min="1", max="600"), choice("timing", "Waktu setoran", [("end", "Akhir bulan"), ("start", "Awal bulan")])], ["Imbal hasil diasumsikan tetap dan dimajemukkan bulanan. Pajak, biaya, dan risiko investasi belum termasuk."])
add("inflation", "Dampak inflasi", "personal", "Perkiraan perubahan harga dan daya beli.", [amount("price", "Harga / nilai uang saat ini"), percent("inflation", "Inflasi tahunan (%)", "3", max="100"), integer("years", "Jangka waktu (tahun)", "5", min="1", max="100")], ["Inflasi diasumsikan tetap. Hasil merupakan proyeksi, bukan prakiraan resmi."])
add("currency", "Konversi mata uang", "personal", "Konversi menggunakan kurs yang Anda tentukan.", [choice("direction", "Arah konversi", [("to-idr", "Valuta asing ke Rupiah"), ("from-idr", "Rupiah ke valuta asing")]), choice("currency", "Mata uang", [("USD", "USD"), ("SAR", "SAR"), ("MYR", "MYR"), ("SGD", "SGD"), ("EUR", "EUR"), ("JPY", "JPY")]), number("amount", "Nominal yang ditukar", min="0.000001"), number("rate", "Kurs Rupiah per 1 unit valuta", min="0.000001"), percent("feeRate", "Biaya penukaran (%)", "0"), amount("fee", "Biaya tetap Rupiah", "0"), field("rateDate", "Tanggal kurs", "date", "today")], ["Kurs diisi manual; bukan kurs langsung. Biaya persentase dihitung dari nilai Rupiah; biaya tetap selalu dalam Rupiah."])
add("loan", "Cicilan pinjaman", "debt", "Rincian angsuran dan total bunga.", [amount("principal", "Pokok pinjaman"), percent("annualRate", "Bunga nominal tahunan (%)", "0", max="100"), integer("months", "Tenor (bulan)", "12", min="1", max="600"), amount("fee", "Biaya administrasi di awal", "0"), choice("method", "Metode bunga", [("annuity", "Anuitas / efektif"), ("flat", "Flat"), ("declining", "Pokok tetap, bunga menurun")])], ["Bunga efektif dihitung dari sisa pokok. Bunga flat dihitung dari pokok awal. Angsuran terakhir menyesuaikan sisa; kontrak bank dapat memakai pembulatan berbeda."])
add("fixed-margin", "Cicilan margin tetap", "debt", "Angsuran berdasarkan harga dan margin yang disepakati.", [amount("price", "Harga pokok barang"), amount("margin", "Total margin yang disepakati", "0"), amount("downPayment", "Uang muka", "0"), amount("fee", "Biaya lain di awal", "0"), integer("months", "Tenor (bulan)", "12", min="1", max="600")], ["Margin diisi nominal total dari akad, bukan persentase bunga tahunan. Biaya administrasi di awal dipisahkan. Hasil tidak menilai keabsahan akad."])
add("debt-payoff", "Pelunasan utang", "debt", "Durasi pelunasan dengan tambahan pembayaran.", [amount("principal", "Sisa pokok utang"), percent("annualRate", "Bunga nominal tahunan (%)", "0", max="100"), amount("payment", "Pembayaran bulanan"), amount("extra", "Tambahan pembayaran bulanan", "0")], ["Bunga diasumsikan efektif bulanan. Pembayaran harus melebihi bunga bulan pertama. Penalti dan biaya pelunasan belum termasuk; simulasi dibatasi 600 bulan."])
add("debt-ratio", "Rasio cicilan", "debt", "Porsi penghasilan yang dipakai membayar cicilan.", [amount("income", "Penghasilan bersih bulanan"), amount("existing", "Total cicilan bulanan saat ini", "0"), amount("newPayment", "Rencana cicilan baru", "0"), percent("limit", "Batas pribadi (%)", "30")], ["Batas rasio adalah pilihan perencanaan pribadi. Persetujuan kredit dan kemampuan bayar bergantung pada kondisi lengkap Anda."])
add("selling-price", "Modal dan harga jual", "business", "Harga jual berdasarkan biaya dan target keuntungan.", [amount("cost", "Modal / biaya per unit"), percent("profit", "Target keuntungan (%)", "20"), choice("basis", "Metode keuntungan", [("markup", "Markup dari modal"), ("margin", "Margin dari harga jual")]), percent("fee", "Biaya platform dari harga jual (%)", "0")], ["Biaya platform dimasukkan dalam harga. Target margin ditambah biaya platform harus kurang dari 100%."])
add("margin", "Margin dan markup", "business", "Laba per unit dan kedua ukuran persentasenya.", [amount("cost", "Modal per unit"), amount("price", "Harga jual per unit")], ["Margin = laba dibagi harga jual. Markup = laba dibagi modal. Harga di bawah modal menghasilkan persentase negatif."])
add("break-even", "Titik impas usaha", "business", "Penjualan minimum untuk menutup biaya.", [amount("fixed", "Biaya tetap per periode"), amount("variable", "Biaya variabel per unit"), amount("price", "Harga jual per unit"), integer("sales", "Rencana unit terjual", "0", max="1000000")], ["Harga jual harus lebih tinggi dari biaya variabel. Unit titik impas dibulatkan ke atas."])

benchmark = [choice("benchmark", "Standar nisab", [("gold", "85 gram emas murni"), ("silver", "595 gram perak murni")]), amount("metalPrice", "Harga per gram logam nisab", min="1"), field("priceDate", "Tanggal harga logam", "date", "today")]
ownership = [check("owned", "Harta dimiliki sempurna"), check("haul", "Telah mencapai satu haul Hijriah")]
debt = [choice("deduction", "Metode pengurang", [("none", "Tanpa pengurangan kewajiban"), ("due", "Kurangi kewajiban yang memenuhi ketentuan")]), amount("liabilities", "Kewajiban jatuh tempo yang boleh dikurangkan", "0", visible={"deduction": "due"})]
zakat_note = ["Gunakan harga dan standar nisab dari rujukan yang Anda pilih. Nilai konversi 20 dinar / 200 dirham ke gram merupakan standar fikih, bukan angka gram dalam hadis.", "Haul mengikuti tahun Hijriah. Pengurangan kewajiban berbeda antar pendapat; masukkan hanya kewajiban yang memang boleh dikurangkan.", "Zakat dibulatkan ke atas ke Rupiah untuk menghindari kekurangan pembayaran."]
zakat_method = "Simulasi zakat harta 2,5% untuk satu haul Hijriah; standar emas 85 gram atau perak 595 gram. Pilihan pengurang dinyatakan secara eksplisit."
add("zakat-maal", "Zakat maal gabungan", "zakat", "Gabungkan harta wajib zakat tanpa menghitung aset dua kali.", [amount("cash", "Uang tunai", "0"), amount("savings", "Tabungan / simpanan", "0"), amount("gold", "Nilai emas wajib zakat", "0"), amount("silver", "Nilai perak wajib zakat", "0"), amount("trade", "Nilai harta perdagangan", "0"), amount("investment", "Nilai investasi wajib zakat", "0"), amount("receivables", "Piutang yang dapat ditagih", "0")] + debt + benchmark + ownership, zakat_note + ["Emas, saham, dan piutang yang sudah masuk nilai usaha tidak dimasukkan lagi. Hasil panen, ternak, dan rikaz dihitung dengan ketentuan masing-masing."], ["q9_103", "b1454", "d1573"], zakat_method)
add("zakat-income", "Zakat penghasilan", "zakat", "Perhitungan penghasilan bulanan atau tahunan.", [amount("income", "Total penghasilan pada periode pilihan"), choice("period", "Periode penghasilan", [("annual", "Tahunan"), ("monthly", "Bulanan")]), choice("basis", "Dasar penghasilan", [("gross", "Bruto"), ("net", "Net setelah pengurang yang diperbolehkan")]), amount("expenses", "Pengurang yang diperbolehkan", "0", visible={"basis": "net"}), amount("goldPrice", "Harga emas murni per gram", min="1"), field("priceDate", "Tanggal harga emas", "date", "today"), check("owned", "Penghasilan telah diterima / dimiliki")], ["Metode Indonesia: nisab tahunan senilai 85 gram emas dan tarif 2,5%, merujuk Fatwa MUI Nomor 3 Tahun 2003.", "Nisab bulanan merupakan pembagian nisab tahunan menjadi 12 untuk pembayaran berkala. Total tahunan tetap perlu direkonsiliasi.", "Tidak ada hadis sahih yang menyebut gaji modern secara khusus. Penerapannya adalah ijtihad atas dalil umum; pilihan bruto/net harus mengikuti rujukan Anda."], ["q9_103", "q2_267", "d1573"], "Metode zakat penghasilan Indonesia, Fatwa MUI Nomor 3 Tahun 2003; pembayaran bulanan adalah pembayaran berkala, bukan haul bulanan.")
add("zakat-savings", "Zakat uang dan tabungan", "zakat", "Hitung simpanan yang memenuhi nisab dan haul.", [amount("assets", "Total uang / tabungan wajib zakat")] + debt + benchmark + ownership, zakat_note + ["Penghasilan yang masih tersimpan dihitung sebagai aset saat penilaian haul; perhatikan zakat yang sudah dibayarkan agar tidak dihitung ganda."], ["q9_103", "b1454", "d1573"], zakat_method)
for metal, label, grams in [("gold", "emas", "85"), ("silver", "perak", "595")]:
    add("zakat-"+metal, "Zakat "+label, "zakat", "Berat murni, nisab, dan nilai zakat.", [number("weight", "Berat total", unit="gram"), percent("purity", "Kadar kemurnian (%)", "100"), amount("price", "Harga logam murni per gram", min="1"), field("priceDate", "Tanggal harga logam", "date", "today"), choice("jewelry", "Perlakuan perhiasan", [("include", "Termasuk perhiasan menurut pendapat yang dipilih"), ("exclude", "Kecualikan perhiasan pemakaian wajar")]), number("jewelryWeight", "Berat perhiasan yang dikecualikan", "0", unit="gram", visible={"jewelry": "exclude"})] + ownership, zakat_note + ["Nisab menggunakan "+grams+" gram logam murni. Perhiasan pemakaian memiliki perbedaan pendapat; aplikasi menampilkan pilihan, tanpa menetapkan satu pendapat untuk semua pengguna."], ["d1573", "b1454"], "Tarif 2,5%; kadar logam dinormalisasi ke berat murni sebelum dibandingkan dengan nisab.")
add("zakat-trade", "Zakat perdagangan", "zakat", "Harta usaha yang diperuntukkan untuk perdagangan.", [amount("inventory", "Persediaan pada harga pasar", "0"), amount("cash", "Kas usaha", "0"), amount("receivables", "Piutang usaha yang dapat ditagih", "0")] + debt + benchmark + ownership, zakat_note + ["Aset tetap operasional, seperti bangunan atau mesin yang tidak dijual, tidak dimasukkan sebagai persediaan.", "Ketentuan perdagangan merupakan penerapan fikih atas dalil umum harta dan hasil usaha."], ["q2_267", "q9_103", "b1454"], zakat_method)
add("zakat-investment", "Zakat investasi", "zakat", "Dasar zakat mengikuti tujuan kepemilikan dan jenis aset.", [choice("purpose", "Metode kepemilikan", [("trading", "Diperdagangkan: nilai pasar + hasil tersimpan"), ("holding", "Dimiliki: bagian aset wajib zakat + hasil tersimpan")]), amount("market", "Nilai pasar investasi", "0", visible={"purpose": "trading"}), amount("eligible", "Bagian aset wajib zakat menurut laporan / rujukan", "0", visible={"purpose": "holding"}), amount("returns", "Hasil investasi yang belum termasuk nilai di atas", "0"), amount("paid", "Zakat yang sudah dibayarkan untuk aset / haul yang sama", "0")] + debt + benchmark + ownership, zakat_note + ["Tidak seluruh nilai aset investasi jangka panjang otomatis menjadi dasar zakat. Gunakan data aset wajib zakat dari penerbit atau rujukan yang sesuai.", "Ketentuan saham dan instrumen modern adalah ijtihad; dalil yang ditampilkan adalah dasar umum zakat harta."], ["q9_103", "q2_267", "b1454"], "Pilih metode perdagangan atau bagian aset wajib zakat untuk kepemilikan jangka panjang. Pembayaran sebelumnya hanya dikurangkan untuk aset dan haul yang sama.")
add("zakat-crops", "Zakat pertanian", "zakat", "Zakat hasil panen berdasarkan nisab dan pengairan.", [number("harvest", "Berat panen yang memenuhi jenis hasil wajib zakat", unit="kg"), number("nisabKg", "Konversi lima wasaq menurut komoditas / rujukan", unit="kg", min="0.000001"), number("price", "Harga hasil panen per kg", unit="Rp/kg", min="0.000001"), choice("irrigation", "Pengairan", [("natural", "Alami: 10%"), ("paid", "Dengan usaha / biaya: 5%"), ("mixed", "Campuran setara: 7,5%")]), check("eligible", "Jenis hasil panen memenuhi ketentuan rujukan")], ["Nisab asal adalah lima wasaq, ukuran volume. Konversi ke kilogram berbeda menurut komoditas; masukkan angka dari lembaga zakat yang dipilih.", "Tarif 10% dan 5% disebut dalam hadis. Tarif 7,5% adalah pendekatan fikih untuk pengairan campuran setara; campuran tidak setara perlu pemeriksaan metode.", "Dihitung ketika panen dan tidak menunggu haul. Hasil kg ditampilkan terlebih dahulu; pembayaran uang mengikuti ketentuan rujukan."], ["q2_267", "b1483", "b1405"], "Nisab lima wasaq; tarif 10%, 5%, atau metode campuran setara 7,5%.")
add("zakat-livestock", "Zakat peternakan", "zakat", "Jumlah hewan zakat sesuai jenis dan jumlah ternak.", [choice("animal", "Jenis ternak", [("sheep", "Kambing / domba"), ("cattle", "Sapi / kerbau"), ("camel", "Unta")]), integer("count", "Jumlah ternak", min="1", max="10000"), check("owned", "Ternak dimiliki sempurna"), check("haul", "Telah mencapai satu haul Hijriah"), check("grazing", "Ternak digembalakan dan bukan hewan kerja")], ["Hasil berupa jenis dan jumlah hewan, bukan persentase nilai uang. Umur hewan pembayaran harus memenuhi syarat.", "Kalkulator memakai tabel zakat ternak gembalaan. Ternak untuk diperjualbelikan memakai Zakat perdagangan; perbedaan ketentuan pemeliharaan mengikuti rujukan.", "Untuk jumlah besar, hasil memilih kombinasi ambang yang mencakup jumlah ternak tanpa melampauinya; pilihan hewan yang setara perlu dibicarakan dengan amil."], ["b1454", "d1576"], "Tabel kambing dan unta dari riwayat Abu Bakar; sapi berdasarkan ketentuan 30/40 dalam riwayat Muadz.")
add("zakat-rikaz", "Zakat rikaz", "zakat", "Seperlima dari harta yang benar-benar termasuk rikaz.", [amount("value", "Nilai harta rikaz"), check("eligible", "Kategori rikaz telah dipastikan oleh pihak berwenang / rujukan")], ["Tarif 20%; tanpa menunggu haul pada metode jumhur. Barang hilang (luqathah), hadiah, dan hasil tambang tidak otomatis termasuk rikaz.", "Kepemilikan dan kewajiban hukum atas temuan harus diselesaikan sebelum menggunakan hasil."], ["b1499"], "Seperlima (20%) untuk kategori rikaz yang telah dipastikan.")
add("zakat-fitrah", "Zakat fitrah", "zakat", "Kebutuhan bahan makanan pokok atau pembayaran uang.", [integer("people", "Jumlah orang", "1", min="1", max="1000"), number("kg", "Konversi satu sha menurut ketentuan daerah", unit="kg/orang", min="0.000001"), choice("payment", "Metode pembayaran", [("food", "Bahan makanan pokok"), ("money", "Uang sesuai ketentuan daerah")]), amount("perPerson", "Ketetapan uang per orang", visible={"payment": "money"})], ["Hadis menyebut satu sha, bukan satu angka kilogram universal. Gunakan ketentuan makanan pokok dan konversi daerah Anda.", "Pembayaran uang merupakan pilihan fikih / ketentuan lembaga; jumlah uang diisi dari ketetapan daerah.", "Waktu pembayaran mengikuti ketentuan zakat fitrah dan dilakukan sebelum salat Id."], ["b1503"], "Satu sha per orang; pilihan uang mengikuti pendapat dan ketentuan daerah yang dipilih.")
add("fidyah", "Fidyah puasa", "obligations", "Jumlah porsi atau nilai pembayaran untuk hari yang wajib fidyah.", [integer("days", "Jumlah hari", min="1", max="10000"), choice("condition", "Dasar kewajiban", [("chronic", "Usia lanjut / sakit menetap, tidak mampu berpuasa"), ("other", "Kondisi lain sudah dikonfirmasi sesuai rujukan")]), choice("payment", "Metode pembayaran", [("food", "Porsi makanan"), ("money", "Uang menurut pendapat / ketentuan yang dipilih")]), amount("perDay", "Nilai makanan / fidyah per hari", min="1"), check("confirmed", "Kewajiban fidyah untuk kondisi ini sudah dipastikan")], ["Sakit sementara dan perjalanan umumnya berkaitan dengan qadha; tidak otomatis diganti fidyah.", "Kehamilan, menyusui, dan keterlambatan qadha memiliki perbedaan pendapat. Gunakan pilihan kondisi lain setelah dasar kewajibannya dipastikan.", "Jenis, ukuran makanan, dan kebolehan uang mengikuti rujukan. Aplikasi menghitung jumlah, tanpa menentukan diagnosis atau kewajiban dari kondisi medis."], ["q2_184", "b4505"], "Satu penerima / porsi yang memenuhi ketentuan per hari; nilai per hari berasal dari rujukan yang dipilih.")
add("kaffarah-oath", "Kafarat sumpah", "obligations", "Kewajiban sepuluh penerima atau puasa bagi yang tidak mampu.", [integer("count", "Jumlah kafarat yang telah dipastikan", "1", min="1", max="1000"), choice("method", "Kemampuan dan bentuk kafarat", [("food", "Mampu: memberi makan sepuluh orang miskin"), ("clothing", "Mampu: memberi pakaian sepuluh orang miskin"), ("fast", "Tidak mampu: puasa tiga hari")]), amount("perPerson", "Biaya makanan / pakaian per penerima", min="1", visible={"method": ["food", "clothing"]}), check("confirmed", "Sumpah dan jumlah kewajiban kafarat sudah dipastikan")], ["Puasa berlaku jika tidak mampu menunaikan bentuk kafarat harta yang disebut dalam ayat; bukan pilihan bebas karena lebih murah.", "Biaya hanya membantu perencanaan pemberian makanan / pakaian. Bentuk pembayaran dan ketentuan puasa mengikuti rujukan.", "Jumlah sumpah yang menghasilkan satu atau beberapa kafarat perlu dipastikan terlebih dahulu."], ["q5_89"], "Al-Maidah 5:89: sepuluh orang miskin; bila tidak mampu, puasa tiga hari.")
add("kaffarah-ramadan", "Kafarat puasa Ramadan", "obligations", "Urutan kewajiban untuk kasus yang memenuhi ketentuan.", [integer("count", "Jumlah kafarat yang telah dipastikan", "1", min="1", max="1000"), choice("stage", "Tahap kewajiban yang berlaku", [("fast", "Tidak dapat membebaskan budak; mampu puasa dua bulan berturut-turut"), ("food", "Tidak mampu tahap sebelumnya; memberi makan 60 orang miskin")]), amount("perPerson", "Biaya makanan per penerima", min="1", visible={"stage": "food"}), check("confirmed", "Jenis pelanggaran dan urutan kewajiban sudah dipastikan")], ["Hadis yang ditampilkan berkaitan dengan hubungan suami istri pada siang Ramadan. Makan/minum sengaja dan kasus lain memiliki perbedaan ketentuan fikih.", "Puasa dua bulan mengikuti dua bulan berturut-turut menurut rujukan, tidak selalu tepat 60 hari kalender. Pengulangan pelanggaran tidak otomatis berarti kafarat dikalikan jumlah hari.", "Kalkulator tidak mengalihkan kewajiban puasa menjadi uang berdasarkan pilihan kenyamanan."], ["b1936"], "Urutan dalam hadis: membebaskan budak; jika tidak mampu, puasa dua bulan berturut-turut; jika tidak mampu, memberi makan 60 orang miskin.")
estate = [amount("estate", "Total harta milik pewaris"), amount("funeral", "Biaya pengurusan jenazah yang wajar", "0"), amount("debts", "Utang dan kewajiban pewaris", "0"), amount("bequest", "Wasiat yang diminta", "0"), check("beneficiaryHeir", "Penerima wasiat termasuk ahli waris"), check("consent", "Semua ahli waris yang berhak sudah dewasa, cakap, dan menyetujui secara sukarela setelah pewaris wafat")]
add("wasiyyah", "Wasiat dan harta warisan bersih", "inheritance", "Selesaikan kewajiban sebelum pembagian warisan.", estate, ["Masukkan hanya harta milik pewaris; pisahkan kepemilikan pasangan / pihak lain terlebih dahulu.", "Batas umum wasiat adalah sepertiga dari sisa setelah pengurusan jenazah dan utang. Wasiat kepada ahli waris dan kelebihan sepertiga memerlukan persetujuan ahli waris yang berhak.", "Persetujuan wasiat khusus diberikan setelah pewaris wafat oleh ahli waris yang dewasa dan cakap, tanpa paksaan. Persetujuan sebagian ahli waris hanya berlaku atas hak mereka; kasus ini atau adanya ahli waris anak memerlukan perhitungan khusus."], ["q4_11", "q4_12", "b2742", "d2870"], "Sisa harta setelah pengurusan jenazah, utang, dan wasiat yang sah; batas sepertiga pada kondisi umum.")
heirs = [choice("sex", "Jenis kelamin pewaris", [("male", "Laki-laki"), ("female", "Perempuan")]), integer("wives", "Istri yang berhak", "0", max="4", visible={"sex": "male"}), check("husband", "Suami yang berhak", visible={"sex": "female"}), check("father", "Ayah hidup"), check("mother", "Ibu hidup"), check("grandfather", "Kakek dari garis ayah hidup"), check("paternalGrandmother", "Nenek dari ayah hidup"), check("maternalGrandmother", "Nenek dari ibu hidup")]
for key, label in [("sons", "Anak laki-laki"), ("daughters", "Anak perempuan"), ("grandsons", "Cucu laki-laki dari anak laki-laki"), ("granddaughters", "Cucu perempuan dari anak laki-laki"), ("brothers", "Saudara laki-laki kandung"), ("sisters", "Saudara perempuan kandung"), ("paternalBrothers", "Saudara laki-laki seayah"), ("paternalSisters", "Saudara perempuan seayah"), ("maternalBrothers", "Saudara laki-laki seibu"), ("maternalSisters", "Saudara perempuan seibu")]: heirs.append(integer(key, label, "0", max="100"))
add("faraid", "Warisan Islam (faraid)", "inheritance", "Bagian tetap, asabah, aul, dan radd dengan rincian per ahli waris.", estate + heirs + [check("scope", "Semua ahli waris sudah dicatat; tidak ada ahli waris lain, kehamilan, orang hilang, beda agama, pembunuhan, atau sengketa kepemilikan")], ["Metode simulasi: faraid Sunni Hanafi. Kakek dari ayah menghalangi saudara; radd berlaku kepada pemilik bagian selain pasangan. Kasus hanya pasangan menampilkan sisa untuk penetapan lebih lanjut.", "Cucu pada form hanya satu tingkat dari anak laki-laki. Keponakan, paman, sepupu, ahli waris lebih jauh, kehamilan, orang hilang, dan kasus penghalang pribadi memerlukan perhitungan khusus; jangan menandai konfirmasi lingkup jika kondisi ini ada.", "Kasus ibu dengan ayah dan pasangan memakai sepertiga sisa (umariyyatain). Bagian istri dibagi antar istri yang berhak.", "Hasil merupakan simulasi pembagian menurut metode tersebut. Persetujuan wasiat khusus tidak mewakili ahli waris anak atau yang tidak cakap. Persetujuan sebagian ahli waris memerlukan perhitungan khusus. Pembagian nyata harus memastikan ahli waris dan hak pihak lain melalui pihak yang berwenang."], ["q4_11", "q4_12", "q4_176", "b6732", "b6736", "b2742", "d2870"], "Faraid Sunni Hanafi untuk ahli waris pada form; perbedaan mazhab dan kondisi khusus dinyatakan pada lingkup perhitungan.")

assert len(catalog) == 38
data = dict(version="2026-10-05.1", categories=[dict(id=i, title=t, icon=s) for i,t,s in categories], sources=sources, calculators=catalog)
(ROOT / "contracts/calculators/catalog.json").write_text(json.dumps(data, ensure_ascii=True, indent=2)+"\n")
